apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: customera-clustery
  name: customer-clustery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-vote-back
  namespace: customerA-clusterY
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-vote-back
  template:
    metadata:
      labels:
        app: public-vote-back
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: public-vote-back
        image: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: public-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: public-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-vote-front
  template:
    metadata:
      labels:
        app: public-vote-front
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: public-vote-front
        image: microsoft/azure-vote-front:v1
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "public-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: public-vote-front
spec:
  ports:
  - port: 80
  selector:
    app: public-vote-front
  type: NodePort
